# Generated by Django 3.0.6 on 2020-11-14 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arret', models.DateTimeField(verbose_name='date arret')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200)),
                ('PAU', models.DecimalField(decimal_places=2, max_digits=19)),
                ('PVU', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(verbose_name='date operation')),
                ('montant_encaisse', models.IntegerField(default=0)),
                ('monnaie_rendue', models.IntegerField(default=0)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Article')),
                ('numero_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Vente')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Decaissement')], max_length=200)),
                ('motif', models.CharField(choices=[('vente', 'Vente'), ('depot_petite_monnaie', 'Depot Petite Monnaie'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('numero_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Vente')),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_entree', models.DateTimeField(verbose_name='date operation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Coupures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupure', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('operation_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.OperationsCaisse')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='date debut')),
                ('date_fin', models.DateTimeField(verbose_name='date fin')),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_avarie', models.DateTimeField(verbose_name='date operation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Categorie'),
        ),
    ]
