# Generated by Django 3.0.2 on 2020-04-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='monnaie_rendue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_encaisse',
            field=models.IntegerField(default=0),
        ),
    ]
