# Generated by Django 3.0.6 on 2020-11-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20201129_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='date_depot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(verbose_name='date vente'),
        ),
        migrations.CreateModel(
            name='TransactionsClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_transaction', models.CharField(max_length=200)),
                ('solde_avant', models.IntegerField(default=0)),
                ('solde_apres', models.IntegerField(default=0)),
                ('date_transaction', models.DateTimeField(verbose_name='date transaction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Client')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Depot')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Vente')),
            ],
        ),
    ]
