# Generated by Django 3.0.2 on 2020-04-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20200404_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Decaissement')], max_length=200)),
                ('motif', models.CharField(choices=[('vente', 'Vente'), ('depot_petite_monnaie', 'Depot Petite Monnaie'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('numero_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Vente')),
            ],
        ),
        migrations.CreateModel(
            name='Especes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billet_ou_piece_de', models.IntegerField(default=0)),
                ('nbr_billet_ou_piece_de', models.IntegerField(default=0)),
                ('numero_operation_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.OperationsCaisse')),
            ],
        ),
    ]
