# Generated by Django 3.0.6 on 2020-11-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20201129_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoriqueClient',
            new_name='HistoriqueTransactionsClient',
        ),
    ]
