# Generated by Django 3.0.2 on 2020-04-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_especes_operationscaisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupure', models.IntegerField(default=0)),
                ('qte', models.IntegerField(default=0)),
                ('numero_operation_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.OperationsCaisse')),
            ],
        ),
        migrations.DeleteModel(
            name='Especes',
        ),
    ]
