# Generated by Django 3.0.6 on 2020-12-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20201129_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avance',
            new_name='Depot',
        ),
        migrations.RenameField(
            model_name='historiquetransactionsclient',
            old_name='avance',
            new_name='depot',
        ),
    ]
