# Generated by Django 3.0.2 on 2020-04-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20200413_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupures',
            old_name='numero_operation_caisse',
            new_name='operation_caisse',
        ),
    ]
