# Generated by Django 3.0.5 on 2020-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20200413_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='PAU',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVU',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
