# Generated by Django 3.0.6 on 2020-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20201201_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_barres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_peremption',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date peremption'),
        ),
    ]
