# Generated by Django 3.0.5 on 2020-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20200421_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='PAU',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVU',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
