# Generated by Django 3.0.6 on 2020-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20201230_1402'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('code_barres',), name='unicite_du_code_barres'),
        ),
    ]
