# Generated by Django 3.0.6 on 2021-01-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20201230_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDepotRamassageCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
            ],
        ),
        migrations.RemoveField(
            model_name='operationscaisse',
            name='numero_vente',
        ),
        migrations.DeleteModel(
            name='Coupures',
        ),
        migrations.DeleteModel(
            name='OperationsCaisse',
        ),
    ]
