# Generated by Django 3.1.4 on 2021-02-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0009_auto_20201230_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDepotRamassageCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='operationscaisse',
            name='numero_vente',
        ),
        migrations.DeleteModel(
            name='Coupures',
        ),
        migrations.DeleteModel(
            name='OperationsCaisse',
        ),
    ]
