# Generated by Django 3.2.9 on 2021-12-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0010_auto_20210209_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteOrangeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='PVG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='prix_vente_article',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom_article',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='HistoriqueDepotRamassageCompteOrangeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
