# Generated by Django 3.2.9 on 2022-01-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20211219_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='PAU',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVG',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVU',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='prix_vente_article',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=19),
        ),
    ]
