# Generated by Django 3.2.9 on 2022-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20220118_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='PAU',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='PVU',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='prix_vente_article',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
