# Generated by Django 3.2.9 on 2022-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20220207_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('solde', models.IntegerField(default=0)),
            ],
        ),
    ]
