# Generated by Django 4.2.3 on 2023-08-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0014_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recu', models.CharField(choices=[('A4', 'A4'), ('Thermique', 'Thermique')], max_length=200)),
                ('afficher_le_nom_du_client_sur_le_recu', models.BooleanField(blank=True, default=False, null=True)),
                ('afficher_le_nom_du_vendeur_sur_le_recu', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='fournisseur',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='solde',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='tel',
        ),
        migrations.AddField(
            model_name='caisse',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.fournisseur'),
        ),
        migrations.AddField(
            model_name='entree',
            name='paye',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='montant_du_au_fournisseur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='historiquedepotramassagecaisse',
            name='caisse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.caisse'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_vente',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='payment_mode',
            field=models.CharField(choices=[('compte', 'Compte'), ('orange_money', 'Orange Money'), ('liquide', 'Liquide')], default='liquide', max_length=12),
        ),
        migrations.AlterField(
            model_name='entree',
            name='date_entree',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date operation'),
        ),
        migrations.CreateModel(
            name='RemboursementFournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date operation')),
                ('montant', models.IntegerField(default=0)),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.entree')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ArretCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arret', models.DateTimeField(auto_now_add=True)),
                ('montant_caisse', models.IntegerField(default=0)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
