# Generated by Django 4.1.5 on 2023-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_parametres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher_le_nom_du_client_sur_le_recu', models.BooleanField(blank=True, default=False, null=True)),
                ('afficher_le_nom_du_vendeur_sur_le_recu', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parametres',
        ),
    ]
