# Generated by Django 4.1.5 on 2023-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_parametre_delete_parametres'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='type_recu',
            field=models.CharField(choices=[('A4', 'A4'), ('Thermique', 'Thermique')], default='Thermique', max_length=200),
            preserve_default=False,
        ),
    ]
