# Generated by Django 3.2.7 on 2021-10-04 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arret', models.DateTimeField(verbose_name='date arret')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date_peremption', models.DateTimeField(blank=True, null=True, verbose_name='date peremption')),
                ('PAU', models.DecimalField(decimal_places=2, max_digits=19)),
                ('PVU', models.DecimalField(decimal_places=2, max_digits=19)),
                ('PVG', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenoms', models.CharField(max_length=200)),
                ('numero_cnib', models.CharField(max_length=200)),
                ('solde', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompteOrangeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('date_depot', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(verbose_name='date vente')),
                ('montant_encaisse', models.IntegerField(default=0)),
                ('monnaie_rendue', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix_vente_article', models.DecimalField(decimal_places=2, max_digits=19)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.article')),
                ('numero_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.vente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTransactionsClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_transaction', models.CharField(max_length=200)),
                ('solde_avant', models.IntegerField(default=0)),
                ('solde_apres', models.IntegerField(default=0)),
                ('date_transaction', models.DateTimeField(verbose_name='date transaction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.depot')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.vente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDepotRamassageCompteOrangeMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDepotRamassageCaisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('ramassage', 'Ramassage')], max_length=200)),
                ('date_operation', models.DateTimeField(verbose_name='date encaissement')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_entree', models.DateTimeField(verbose_name='date operation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.article')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='date debut')),
                ('date_fin', models.DateTimeField(verbose_name='date fin')),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_avarie', models.DateTimeField(verbose_name='date operation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.categorie'),
        ),
    ]
